network:
  version: 2
  ethernets:
    enp0s8:
      dhcp4: false
      addresses:
        - 192.168.2.2/24
      routes:
        - to: 192.168.2.0/24    #host-only network routing
          via: 192.168.2.2
        - to: default           #internet nat network routing (default gateway)
          via: 10.0.2.4