network:
  version: 2
  ethernets:
    enp0s3:
      dhcp4: false
      addresses:
        - 192.168.2.3/24
      routes:
        - to: default         #default gateway routes to the machine-A with internet access
          via: 192.168.2.2    #machine-a ip address in the host-only network
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]