services:
  nginx:
    image: nginx:1.25.3-alpine3.18
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
  webapp:
    image: strm/helloworld-http